package bank.system;

import javax.swing.ButtonGroup;

import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class SignupThree extends javax.swing.JFrame {
    private String formno;
    
    public SignupThree(int formno) {
        this.formno = String.valueOf(formno);
        initComponents();
        
        ButtonGroup raceGroup = new ButtonGroup();
        raceGroup.add(radioSavings);
        raceGroup.add(radioFixed);
        raceGroup.add(radioCurrent);
        raceGroup.add(radioRecurring);
        
        // Set default selection
        radioSavings.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        radioSavings = new javax.swing.JRadioButton();
        radioCurrent = new javax.swing.JRadioButton();
        radioFixed = new javax.swing.JRadioButton();
        radioRecurring = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showPinCheck = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        atmCheck = new javax.swing.JCheckBox();
        internetBankingCheck = new javax.swing.JCheckBox();
        mobileCheck = new javax.swing.JCheckBox();
        emailCheck = new javax.swing.JCheckBox();
        chequeCheck = new javax.swing.JCheckBox();
        eStatementCheck = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel1.setText("Page 3: Account Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Type"));

        radioSavings.setText("Savings Account");

        radioCurrent.setText("Current Account");

        radioFixed.setText("Fixed Deposit Account");

        radioRecurring.setText("Recurring Deposit Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(radioSavings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioRecurring, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(radioFixed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioSavings))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(radioFixed)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCurrent)
                    .addComponent(radioRecurring))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Card Details"));

        jLabel2.setText("Card Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        jLabel3.setText("Your 16 Digit Card Number");

        jLabel4.setText("Pin:");

        jLabel5.setText("XXXX-XXXX-XXXX-1234");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        jLabel6.setText("Your 4 Digit Pin");

        showPinCheck.setText("Show Pin");
        showPinCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPinCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPinCheck)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pinField)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(showPinCheck))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Services Required"));

        atmCheck.setText("ATM Card");

        internetBankingCheck.setText("Internet Banking");

        mobileCheck.setText("Mobile Banking");

        emailCheck.setText("Email & SMS Banking");

        chequeCheck.setText("Cheque Book");

        eStatementCheck.setText("E-Statement");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atmCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(internetBankingCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(mobileCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(chequeCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eStatementCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atmCheck)
                    .addComponent(emailCheck))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetBankingCheck)
                    .addComponent(chequeCheck))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileCheck)
                    .addComponent(eStatementCheck))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jCheckBox7.setText("I hereby delcare that the above entered details are correct to the best of my knowledge.");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox7)
                            .addComponent(submitBtn))
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submitBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        handleSubmit();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to cancel?", "Confirm Cancel",
            JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void showPinCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPinCheckActionPerformed
        if (showPinCheck.isSelected()) {
            pinField.setEchoChar((char) 0); // Show text
        } else {
            pinField.setEchoChar('*'); // Mask text
        }
    }//GEN-LAST:event_showPinCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> {
            new SignupThree(1).setVisible(true); // example userId = 1
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox atmCheck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox chequeCheck;
    private javax.swing.JCheckBox eStatementCheck;
    private javax.swing.JCheckBox emailCheck;
    private javax.swing.JCheckBox internetBankingCheck;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox mobileCheck;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JRadioButton radioCurrent;
    private javax.swing.JRadioButton radioFixed;
    private javax.swing.JRadioButton radioRecurring;
    private javax.swing.JRadioButton radioSavings;
    private javax.swing.JCheckBox showPinCheck;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

   private void handleSubmit() {
        submitBtn.setEnabled(false); // Prevent multiple submissions
        
        try {
            String accountType = getSelectedAccountType();
            if (accountType == null) {
                JOptionPane.showMessageDialog(this, "Please select an account type.");
                return;
            }

            String pin = validatePin();
            if (pin == null) return;

            if (!jCheckBox7.isSelected()) {
                JOptionPane.showMessageDialog(this, "Please accept the declaration.");
                return;
            }

            String cardNumber = generateCardNumber();
            String services = getSelectedServices();
            if (services == null) return;

            if (saveOrUpdateAccountDetails(accountType, pin, cardNumber, services)) {
                showSuccessMessage(cardNumber, pin);
                navigateToLoginForm();
            }
        } finally {
            submitBtn.setEnabled(true);
        }
    }

   private String getSelectedAccountType() {
        if (radioSavings.isSelected()) return "Savings Account";
        if (radioCurrent.isSelected()) return "Current Account";
        if (radioFixed.isSelected()) return "Fixed Deposit Account";
        if (radioRecurring.isSelected()) return "Recurring Deposit Account";
        return null;
    }

   private String validatePin() {
        String pin = new String(pinField.getPassword()).trim();
        if (!pin.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "PIN must be exactly 4 digits.");
            return null;
        }
        return pin;
    }
   
    private String generateCardNumber() {
        // Generate 16-digit card number starting with "5040"
        return "5040" + String.format("%012d", (long)(Math.random() * 1_000_000_000_000L));
    }
    
    private String getSelectedServices() {
        StringBuilder services = new StringBuilder();
        if (atmCheck.isSelected()) services.append("ATM Card, ");
        if (internetBankingCheck.isSelected()) services.append("Internet Banking, ");
        if (mobileCheck.isSelected()) services.append("Mobile Banking, ");
        if (emailCheck.isSelected()) services.append("Email & SMS Banking, ");
        if (chequeCheck.isSelected()) services.append("Cheque Book, ");
        if (eStatementCheck.isSelected()) services.append("E-Statement, ");
    
        if (services.length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select at least one service.");
            return null;
        }
    
        // Remove last comma and space
        return services.substring(0, services.length() - 2);
    }
    
    private boolean saveOrUpdateAccountDetails(String accountType, String pin, String cardNumber, String services) {
        try (Connection con = DBConnection.getConnection()) {
            // First check if record exists
            if (accountDetailsExist(con)) {
                updateAccountDetails(con, accountType, pin, cardNumber, services);
                return true;
            } else {
                insertAccountDetails(con, accountType, pin, cardNumber, services);
                return true;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error saving account details: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean accountDetailsExist(Connection con) throws SQLException {
        String sql = "SELECT formno FROM signupthree WHERE formno = ?";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, formno);
            try (ResultSet rs = pst.executeQuery()) {
                return rs.next();
            }
        }
    }
    
    private void insertAccountDetails(Connection con, String accountType, String pin, 
                                   String cardNumber, String services) throws SQLException {
        String sql = "INSERT INTO signupthree (formno, account_type, pin, card_number, services) " +
                     "VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, formno);
            pst.setString(2, accountType);
            pst.setString(3, pin);
            pst.setString(4, cardNumber);
            pst.setString(5, services);
            pst.executeUpdate();
        }
    }
 
    private void updateAccountDetails(Connection con, String accountType, String pin, 
                                    String cardNumber, String services) throws SQLException {
        String sql = "UPDATE signupthree SET account_type = ?, pin = ?, " +
                     "card_number = ?, services = ? WHERE formno = ?";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, accountType);
            pst.setString(2, pin);
            pst.setString(3, cardNumber);
            pst.setString(4, services);
            pst.setString(5, formno);
            pst.executeUpdate();
        }
    }

    private void showSuccessMessage(String cardNumber, String pin) {
        JOptionPane.showMessageDialog(this,
            "Account created successfully!\n\n" +
            "Card Number: " + cardNumber + "\n" +
            "PIN: " + pin + "\n\n" +
            "Please use these credentials to login.",
            "Account Created",
            JOptionPane.INFORMATION_MESSAGE);
    }
    
     private void navigateToLoginForm() {
        this.dispose(); // Close current window
        new LoginForm().setVisible(true); // Open login form
    }
}
